server:
  port: 8080

spring:
  messages:
    basename: i18n.messages
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lsc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    data: classpath:data.sql


logging:
  level:
    root: INFO
    org.hibernate: INFO

management:
  security:
    enabled: false