server:
  port: 8081

management:
  security:
    enabled: false

spring:
  application:
    name: movie
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true